#!/usr/bin/env ruby
#^syntax detection

moduledir 'modules/thirdparty'

forge 'https://forgeapi.puppetlabs.com'


mod 'camptocamp/accounts',
    :git => 'git://github.com/camptocamp/puppet-accounts',
    :tag => '1.8.1'

mod 'puppetlabs/apache',
    :git => 'git://github.com/puppetlabs/puppetlabs-apache',
    :tag => '1.10.0'

mod 'puppetlabs/concat',
    :git => 'git://github.com/puppetlabs/puppetlabs-concat',
    :tag => '2.2.0'

mod 'stahnma/epel', 
    :git => 'git://github.com/stahnma/puppet-module-epel',
    :tag => '1.2.2'

#mod 'NYULibraries/fedora_repository',
#    :git => 'git://github.com/NYULibraries/puppet-fedora_repository'
#    #:tag => '0.1.0'

#mod 'golja/gnupg',
mod 'n1tr0g/gnupg',
    :git => 'git://github.com/n1tr0g/golja-gnupg.git',
    :tag => '1.2.3'

mod 'puppetlabs/inifile',
    :git => 'git://github.com/puppetlabs/puppetlabs-inifile.git',
    :tag => '1.6.0'

mod 'voxpupuli/hiera',
        :git => 'https://github.com/voxpupuli/puppet-hiera.git',
        :tag => 'v2.4.0'

mod 'puppetlabs/inifile',
    :git => 'git://github.com/puppetlabs/puppetlabs-inifile',
    :tag => '1.5.0'

mod 'puppetlabs/java',
    :git => 'git://github.com/puppetlabs/puppetlabs-java',
    :tag => '1.6.0'

mod 'yo61/logrotate',
    :git => 'git://github.com/yo61/puppet-logrotate',
    :tag => 'v1.4.0'

mod 'NYULibraries/loris',
    :git => 'git://github.com/NYULibraries/puppet-loris'

mod 'puppetlabs/mysql',
    :git => 'git://github.com/puppetlabs/puppetlabs-mysql',
    :tag => '3.8.0'

mod 'puppetlabs/ntp',
    :git => 'git://github.com/puppetlabs/puppetlabs-ntp',
    :tag => '6.0.0'

mod 'stankevich/python',
    :git => 'git://github.com/stankevich/puppet-python',
    :tag => '1.14.0'

mod 'zack/r10k',
    :git => 'git://github.com/acidprime/r10k',
    :tag => 'v3.2.0'

mod 'jdowning/rbenv',
    :git => 'git://github.com/justindowning/puppet-rbenv',
    :tag => '2.2.0'

mod 'maestrodev/rvm',
   :git => 'git://github.com/maestrodev/puppet-rvm',
   :tag => 'v1.13.1'

mod 'golja/s3cmd',
    :git => 'git://github.com/n1tr0g/golja-s3cmd',
    :tag => '0.1.0'

mod 'voxpupuli/staging',
    :git => 'git://github.com/voxpupuli/puppet-staging',
    :tag => 'v1.0.7'

mod 'puppetlabs/stdlib',
    :git => 'git://github.com/puppetlabs/puppetlabs-stdlib',
    :tag => '4.15.0'

mod 'petems/swap_file',
        :git => 'git://github.com/petems/petems-swap_file',
        :tag => 'v3.0.2'

mod 'puppetlabs/vcsrepo',
    :git => 'git://github.com/puppetlabs/puppetlabs-vcsrepo',
    :tag => '1.3.2'

mod 'puppetlabs/tomcat',
    :git => 'git://github.com/puppetlabs/puppetlabs-tomcat',
    :tag => '1.6.0'

#mod 'aco/yum_autoupdate',
#    :git => 'git://github.com/antoineco/aco-yum_autoupdate',
#    :ref => '0.6.3'

mod 'treydock/yum_cron',
    :git => 'git://github.com/treydock/puppet-yum_cron.git',
    :tag => '2.0.0'

mod 'flannon/archivesspace',
    :git => 'git://github.com/flannon/puppet-archivesspace.git',
    :ref => '0.1.4'
    #:ref => 'master'

mod 'flannon/archivesspace_dev',
    :git => 'git://github.com/flannon/puppet-archivesspace_dev.git',
    :ref => 'master'

mod 'puppetlabs/firewall',
    :git => 'git://github.com/puppetlabs/puppetlabs-firewall.git',
    :ref => '1.8.1'

#mod 'Sliim/pyenv',
#    :git => 'git://github.com/Sliim/puppet-pyenv.git',
#    :tag => '0.1.1'

#mod 'daenney/pyenv',
mod 'flannon/pyenv',
    :git => 'git://github.com/flannon/puppet-pyenv.git'

mod 'Mylezeem/repoforge', 
     :git => 'git://github.com/Mylezeem/puppet-repoforge.git',
     :ref => "0.2.1"

